// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/hashicorp/vault/api"

	mock "github.com/stretchr/testify/mock"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, authMethod
func (_m *Auth) Login(ctx context.Context, authMethod api.AuthMethod) (*api.Secret, error) {
	ret := _m.Called(ctx, authMethod)

	var r0 *api.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.AuthMethod) (*api.Secret, error)); ok {
		return rf(ctx, authMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.AuthMethod) *api.Secret); ok {
		r0 = rf(ctx, authMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.AuthMethod) error); ok {
		r1 = rf(ctx, authMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
