---
run:
  timeout: 10m
  # Specify concurrency level for linting
  concurrency: 4

issues:
  exclude-dirs:
    - vendor
    - .git
    - _tools

linters-settings:
  gocyclo:
    # Set cyclomatic complexity threshold (adjust as needed)
    enabled: true
    threshold: 15
  govet: {}
  funlen:
    lines: 180
  wrapcheck:
    ignoreSigs:
      - multierr.Append
  gofmt:
    # Use gofumpt instead of gofmt
    gofumpt: true

linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - durationcheck
    - gochecknoinits
    - testpackage
    - gci
    - tagliatelle
    - ireturn
    - wrapcheck
    - depguard
    - exhaustruct
    - varnamelen
    - noctx
    - err113
    - gofumpt
    - tenv
    # review below
    - forcetypeassert
    - contextcheck
    - revive
    - paralleltest
    - tparallel
    - mnd
