# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-cluster-replication.fullname" . }}
type: Opaque
data:
  config_file.yaml: {{ .Values.Config.data | b64enc | quote }}
