---
replication:
  - active: "http://localhost:8200"
    sync_to:
      - "http://localhost:8300"
credentials:
  - name: "http://localhost:8200"
    appRole: "vaultClusterReplication"
    secretID: "root"
  - name: "http://localhost:8300"
    appRole: "vaultClusterReplication"
    secretID: "root"
